### ISSUE TITLE
ビジネスルール関連図で package-info.java を読み込まないようにする

### ISSUE THREAD

**Issue by tango238** [irof/jig-erd#60]
ビジネスルール関連図に `package-info.java` が表示されてしまう。
![image](https://user-images.githubusercontent.com/123510/152111463-f35f374d-f59a-4fc6-808a-2afa2c548b9e.png)

**Comment by irof** [comment]
oh...
`package-info` のclassファイルできてるんですかね？
可能なら再現できる構成をいただけると。。。


ところでこちら jig-erd なので dddjava/jig の方にお願いします。。

**Comment by tango238** [comment]
間違えました・・・
